#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d L1 L2 L3
bspc monitor DP-0 -d C1 C2 C3
bspc monitor HDMI-0 -d R1 R2 R3

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config -m DP-0 top_padding 35px
bspc config -m DP-2 top_padding 0px
bspc config -m HDMI-0 top_padding 0px
bspc rule -a polybar private

bspc config active_border_color '#c896fa'
bspc config normal_border_color '#c896fa'
bspc config focused_border_color '#46c8a0'

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# xprop
bspc rule -a firefox desktop='^1'
bspc rule -a discord desktop='^3'
bspc rule -a Tilix desktop='^9'
bspc rule -a 'YouTube Music' desktop='^9'
